### ISSUE TITLE
[Feature Request] Please Add this extension to firefox.

### ISSUE THREAD

**Issue by Talha76** [importlogic/cf-getrating-extension#1]
I searched in the firefox add-ons, but didn't find such extension. Please add this extension to firefox add-ons.

**Comment by importlogic** [comment]
Feature Request acknowledged. Working on it right now, will update on Codeforces and close this issue once it is done.

**Comment by importlogic** [comment]
The extension is now available on Firefox Addons Store as well you can download it from [here](https://addons.mozilla.org/en-US/firefox/addon/cf-getrating).
